In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("소상공인시장진흥공단_상가업소정보_의료기관_201909.csv",low_memory=False)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91335 entries, 0 to 91334
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상가업소번호     91335 non-null  int64
 1   상호명        91335 non-null  object
 2   지점명        1346 non-null   object
 3   상권업종대분류코드  91335 non-null  object
 4   상권업종대분류명   91335 non-null  object
 5   상권업종중분류코드  91335 non-null  object
 6   상권업종중분류명   91335 non-null  object
 7   상권업종소분류코드  91335 non-null  object
 8   상권업종소분류명   91335 non-null  object
 9   표준산업분류코드   86413 non-null  object
 10  표준산업분류명    86413 non-null  object
 11  시도코드       90956 non-null  float64
 12  시도명        90956 non-null  object
 13  시군구코드      90956 non-null  float64
 14  시군구명       90956 non-null  object
 15  행정동코드      91335 non-null  int64
 16  행정동명       90956 non-null  object
 17  법정동코드      91280 non-null  float64
 18  법정동명       91280 non-null  object
 19  지번코드       91335 non-null  int64
 20  대지구분코드     91335 non-null  int64
 21  대지구분명      91335 non-null  object
 22  지번본번지      91335 non-null  int64
 23  지번부번지      72079 non-null  float64
 24  지번주소       91335 non-null  object
 25  도로명코드      91335 non-null  int64
 26  도로명        91335 non-null  object
 27  건물본번지      91335 non-null  int64
 28  건물부번지      10604 non-null  float64
 29  건물관리번호     91335 non-null  object
 30  건물명        46453 non-null  object
 31  도로명주소      91335 non-null  object
 32  구우편번호      91323 non-null  float64
 33  신우편번호      91333 non-null  float64
 34  동정보        7406 non-null   object
 35  층정보        44044 non-null  object
 36  호정보        15551 non-null  object
 37  경도         91335 non-null  float64
 38  위도         91335 non-null  float64
dtypes: float64(9), int64(7), object(23)
memory usage: 27.2+ MB

In [4]:
df.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [5]:
df["상권업종대분류명"]

0        의료
1        의료
2        의료
3        의료
4        의료
         ..
91330    의료
91331    의료
91332    의료
91333    의료
91334    의료
Name: 상권업종대분류명, Length: 91335, dtype: object

In [6]:
# medical에는 df에서 "상권업종대분류명"이 "의료"인 것만 True로 표시
# 나머지는 False로 되어 있는 시리즈
df["상권업종대분류명"] == "의료"

0        True
1        True
2        True
3        True
4        True
         ...
91330    True
91331    True
91332    True
91333    True
91334    True
Name: 상권업종대분류명, Length: 91335, dtype: bool

In [7]:
#두 가지 조건을 만족하는 데이터 가져오기
df[(df["상권업종소분류명"] == "약국") & (df["시도명"] == "서울특별시")]
df[(df["상권업종소분류명"] == "약국") | (df["상권업종소분류명"] == "산부인과")]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19956873,하나산부인과,NaN,S,의료,S01,병원,S01B10,산부인과,Q86201,...,4127310900110810000010857,산호한양아파트,경기도 안산시 단원구 달미로 10,425764.0,15236.0,NaN,NaN,NaN,126.814295,37.336344
4,20364049,더블유스토어수지점,수지점,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4146510100107120002026238,NaN,경기도 용인시 수지구 문정로 32,448170.0,16837.0,NaN,1,NaN,127.095522,37.323528
10,21057519,민생약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4889046030200780002048274,NaN,경상남도 합천군 용주면 월평길 149-35,678912.0,50212.0,NaN,NaN,NaN,128.118615,35.575962
15,21006553,상명약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4713010800103400004022515,NaN,경상북도 경주시 금성로 281,780943.0,38156.0,NaN,1,NaN,129.206670,35.842804
16,21026027,햇살약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4117310100111010002005070,샛별한양아파트,경기도 안양시 동안구 달안로 61,431719.0,14043.0,NaN,NaN,NaN,126.948953,37.396502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91312,16131397,큰나무약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4128110600107000011013834,신원당빌딩,경기도 고양시 덕양구 고양대로 1361,412807.0,10464.0,NaN,1,NaN,126.835684,37.655048
91321,16130841,복음약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,2729012400102760000029818,그린맨션3차아파트,대구광역시 달서구 구마로36길 33,704752.0,42735.0,301,NaN,105,128.547352,35.836250
91322,16091491,설연화한복감성약방,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,1126010400101740001009985,NaN,서울특별시 중랑구 공릉로 28,131848.0,2034.0,NaN,NaN,NaN,127.078082,37.613194
91324,16109731,위례수약국,NaN,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4113110800101810002000002,NaN,경기도 성남시 수정구 위례서일로 18,461210.0,13647.0,NaN,1,NaN,127.137870,37.465260
91330,16196725,온누리약국,베스트,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,3017011200115070000021096,NaN,대전광역시 서구 문예로 67,302831.0,35240.0,NaN,NaN,NaN,127.389865,36.352728

In [8]:
# medicalㅏ에는 df에서 "상권업종대분류명"이 "의료"인 것만 True로 표시
# 나머지는 False로 되어 있는 시리즈
medical = df["상권업종대분류명"] == "의료"

# df.loc[시리즈(True/False),"원하는 컬럼의 이름"]
# "상권업종대분류명"이 "의료"인 자료에서 "상권업종중분류명" 컬럼만 가지는 시리즈  리턴
df.loc[medical,"상권업종중분류명"]

0              병원
1              병원
2              병원
3              병원
4          약국/한약방
           ...
91330      약국/한약방
91331    의료관련서비스업
91332          병원
91333          병원
91334          병원
Name: 상권업종중분류명, Length: 91335, dtype: object

In [9]:
df["상호명"].value_counts()

리원              152
온누리약국           149
경희한의원           141
우리약국            119
중앙약국            111
               ...
메리디언치과            1
이엘피부과성형외과         1
금오중국한의원           1
오케이연합의원           1
천안김안과천안역본점의원      1
Name: 상호명, Length: 56910, dtype: int64

In [10]:
df["상호명"].str.contains("종합병원")

0        False
1        False
2        False
3        False
4        False
         ...
91330    False
91331    False
91332    False
91333    False
91334    False
Name: 상호명, Length: 91335, dtype: bool

In [11]:
df["상호명"].str.endswith("의원").value_counts()

False    52161
True     39174
Name: 상호명, dtype: int64

In [12]:
df_seoul_hospital = df[(df["상권업종소분류명"] == "종합병원") & (df["시도명"] == "서울특별시")].copy()
df_seoul_hospital.head(2)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
305,25155642,대진의료재단,NaN,S,의료,S01,병원,S01B01,종합병원,Q86101,...,1121510100100580025000733,재단법인대순진리회,서울특별시 광진구 긴고랑로 119,143220.0,4944.0,NaN,NaN,NaN,127.088279,37.559048
353,20471487,홍익병원별관,NaN,S,의료,S01,병원,S01B01,종합병원,Q86101,...,1147010100108970013001044,홍익병원별관,서울특별시 양천구 국회대로 250,158070.0,7937.0,NaN,1,NaN,126.862805,37.529213

In [13]:
# '서울특별시'에 위치한 '종합병원'의 상호명 데이터 중, "종합병원"을 포함하는 데이터 인덱싱하기
df_seoul_hospital.loc[~df_seoul_hospital["상호명"].str.contains("종합병원"), "상호명"].unique()

array(['대진의료재단', '홍익병원별관', 'SNUH', '평화드림여의도성모병원의료기매장', '한양', '백산의료재단친구병원',
       '서울보훈병원', '서울성모병원장례식장꽃배달', '서울대학교병원', '알콜중독및정신질환상담소',
       '강남성모병원장례식장꽃배달', '제일병원', '이랜드클리닉', '사랑나눔의료재단', '우울증센터', '성심의료재단',
       '다나의료재단', '서울아산병원신관', '원자력병원장례식장', '국민의원', '고려대학교구로병원', '학교법인일송학원',
       '삼성의료원장례식장', '희명스포츠의학센터인공신장실', '연세대학교의과대학강남세브란스', '국립정신병원',
       '코아클리닉', '수서제일의원', '사랑의의원', '한국전력공사부속한일병원', '신촌연세병원', '창동제일의원',
       '영동세브란스병원', '제일성심의원', '삼성의료재단강북삼성태', '서울시립보라매병원', '서울이의원',
       '서울대학교병원비상계획외래', '평화드림서울성모병원의료', '홍익병원', '사랑나눔의료재단서', '독일의원',
       '서울연합의원', '우신향병원', '동부제일병원', '아산재단금강병원', '명곡안연구소', '아산재단서울중앙병원',
       '메디힐특수여객', '삼성생명공익재단삼성서', '성광의료재단차병원', '한국건강관리협회서울특',
       '정해복지부설한신메디피아', '성베드로병원', '성애의료재단', '실로암의원', 'Y&T성모마취과', '광진성모의원',
       '서울현대의원', '이노신경과의원', '송정훼밀리의원', '서울중앙의원', '영남의료재단', '인제대학교서울백병원',
       '한국필의료재단', '세브란스의원', '가톨릭대학교성바오로병원장례식장', '서울연세의원', '사랑의병원',
       '성삼의료재단미즈메디병원', '씨엠충무병원', '성신의원', '원진재단부설녹색병원', '송파제일의원',
       '카톨릭성모의원', '한양성심의원', '관악성모의원', '강남센트럴병원', '우이한솔의원', '우리들병원',
       '서울성모병원어린이집', '건국대학교병원', '서울적십자병원', '북부성모의원', '한림대학교부속한강성심병원장례식장',
       '서울성모병원응급의료센터', '라마르의원', '가톨릭대학교여의도성모병원', '씨엠병원'], dtype=object)

In [14]:
# 꽃배달, 의료기, 장례식장, 상담소, 어린이집을 포함한 데이터 drop_row에 저장
drop_row1 = df_seoul_hospital[df_seoul_hospital["상호명"].str.contains("꽃배달|의료기|장례식장|상담소|어린이집")].index
drop_row1 = drop_row1.tolist()
drop_row1

[1917, 2803, 4431, 4644, 7938, 10283, 47008, 60645, 70177]

In [15]:
#의원으로 끝나는 데이터 인덱싱
drop_row2 = df_seoul_hospital[df_seoul_hospital["상호명"].str.endswith("의원")].index
drop_row2 = drop_row2.tolist()
drop_row2

[8479,
 12854,
 13715,
 14966,
 16091,
 18047,
 20200,
 20415,
 30706,
 32889,
 34459,
 34720,
 35696,
 37251,
 45120,
 49626,
 51575,
 55133,
 56320,
 56404,
 56688,
 57551,
 62113,
 76508]

In [16]:
drop_row = drop_row1 + drop_row2
print(df_seoul_hospital.shape)
df_seoul_hospital = df_seoul_hospital.drop(drop_row, axis=0)
print(df_seoul_hospital.shape)

(91, 39)
(58, 39)